name: careplus_mobile
description: CarePlus Mobile App scaffold (Flutter) â€” Telemedicine, Payments, Pharmacy, Notifications, Offline cache
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  path: ^1.8.3
  connectivity_plus: ^4.0.1
  geolocator: ^9.0.2
  jitsi_meet: ^4.0.0
  flutter_local_notifications: ^12.0.4
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.0
  flutter_stripe: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true